server.http2.enabled=true
server.port=${SERVER_PORT:8080}
server.ssl.enabled=${SSL_ENABLED:false}
server.ssl.key-store=${SSL_KEY_STORE:}
server.ssl.key-store-type=${SSL_KEY_STORE_TYPE:PKCS12}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD:}
